# Generated by Django 3.0 on 2020-04-04 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(default='Sin genero', max_length=50)),
                ('puntuacion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sinopsis', models.TextField(null=True)),
            ],
        ),
    ]
