# Generated by Django 3.0 on 2020-04-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='films',
            table='films',
        ),
    ]
