# Generated by Django 3.0 on 2020-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_films', '0002_auto_20200404_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='fecha_lanzamiento',
            field=models.DateTimeField(),
        ),
    ]
